services:
  backend:
    build:
      context: flask
      target: deploy
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    ports:
      - 8080:8080
    depends_on:
      -  mongo

  mongo:
    image: mongo
